version: '3'
services:

  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "80:80"
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    depends_on:
      - db
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql --user 1000
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
