version: '3'
services:

  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    #      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    #      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
